[package]
name = "go-cosmwasm"
version = "0.8.0-dev"
authors = ["Ethan Frey <ethanfrey@users.noreply.github.com>"]
edition = "2018"
description = "Go bindings for cosmwasm contracts"
repository = "https://github.com/CosmWasm/go-cosmwasm"
license = "Apache-2.0"
readme = "README.md"
exclude = [".circleci/*", ".gitignore"]

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[badges]
circle-ci = { repository = "CosmWasm/go-cosmwasm", branch = "master" }
maintenance = { status = "actively-developed" }

[features]
default = ["singlepass", "backtraces"]
backtraces = ["snafu/backtraces"]
singlepass = ["cosmwasm-vm/default-singlepass"]
cranelift = ["cosmwasm-vm/default-cranelift"]

[dependencies]
# TODO: enable iterator feature (once everything compiles)
cosmwasm-std = { git = "https://github.com/CosmWasm/cosmwasm", rev = "c3fcea0b70c714ab86d0f401e901be79972f34d3" }
cosmwasm-vm = { git = "https://github.com/CosmWasm/cosmwasm", rev = "c3fcea0b70c714ab86d0f401e901be79972f34d3" }
errno = "0.2"
snafu = "0.6.3"

[build-dependencies]
cbindgen = { version = "0.14" }

[profile.release]
opt-level = 3
debug = false
rpath = true
lto = false
debug-assertions = false
codegen-units = 16
panic = 'unwind'
incremental = true
overflow-checks = true
