[package]
name = "go-cosmwasm"
version = "0.1.0"
authors = ["Ethan Frey <ethanfrey@users.noreply.github.com>"]
edition = "2018"
description = "Go bindings for cosmwasm contracts"
repository = "https://github.com/confio/go-cosmwasm"
license = "Apache-2.0"
readme = "README.md"
exclude = [".circleci/*", ".gitignore"]

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[badges]
circle-ci = { repository = "confio/go-cosmwasm", branch = "master" }
maintenance = { status = "actively-developed" }

[dependencies]
cosmwasm = "0.2"
cosmwasm-vm = "0.2"
errno = "0.2"
failure = "0.1.6"

[build-dependencies]
cbindgen = { version = "0.9.1" }

[profile.release]
opt-level = 3
lto = true
panic = "unwind"