version: 2

jobs:
  build:
    docker:
      - image: circleci/rust:1.41-stretch
    steps:
      - run: rustup toolchain install nightly
      - checkout
      - run: make build-rust
      - persist_to_workspace:
          root: ./api
          paths:
            - libgo_cosmwasm.so

  test:
    working_directory: /go/src/github.com/confio/go-cosmwasm
    docker:
      - image: circleci/golang:1.14
    environment:
      GORACE: "halt_on_error=1"
      BUILD_VERSION: $(echo ${CIRCLE_SHA1} | cut -c 1-10)
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/builds
      - run: cp /tmp/builds/libgo_cosmwasm.so ./api
      - run: make test
      - run: make build-go

  release:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - add_ssh_keys:
          fingerprints:
            - "31:de:e5:84:1b:12:81:94:aa:06:50:c0:cb:bd:79:f0"
      - checkout
# TODO: re-enable for merge
#      - run: make release
      - run: ls -l ./api
      - run: git config user.email "bot@circleci.com"
      - run: git config user.name "CircleCI Bot"
      - run: git add .
      # CIRCLE_BRANCH doesn't give us info, assume it is master
#      - run: git checkout master
      - run: git commit --allow-empty -m '[skip ci] Built release libraries'
      - run: git push origin $CIRCLE_BRANCH
#      - run: git push origin master

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - release:
      # release only on master, not on tags (auto-build on merge PR)
      - release:
#          filters:
#            tags:
#              ignore:
#                - /.*/
#            branches:
#              only:
#                - master
