version: 2
jobs:
  build:
    docker:
      - image: circleci/rust:1.41-stretch
    steps:
      - run: rustup toolchain install nightly
      - checkout
      - run: make build-rust
  test:
    working_directory: /go/src/github.com/confio/go-cosmwasm
    docker:
      - image: circleci/golang:1.14
    environment:
      GORACE: "halt_on_error=1"
      BUILD_VERSION: $(echo ${CIRCLE_SHA1} | cut -c 1-10)
    steps:
      - checkout
      - run: make test
      - run: make build-go
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
