version: 2

jobs:
  build:
    docker:
      - image: circleci/rust:1.41-stretch
    steps:
      - run: rustup toolchain install nightly
      - checkout
      - run: make build-rust
      - persist_to_workspace:
          root: ./api
          paths:
            - libgo_cosmwasm.so
  test:
    working_directory: /go/src/github.com/confio/go-cosmwasm
    docker:
      - image: circleci/golang:1.14
    environment:
      GORACE: "halt_on_error=1"
      BUILD_VERSION: $(echo ${CIRCLE_SHA1} | cut -c 1-10)
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/builds
      - run: cp /tmp/builds/libgo_cosmwasm.so ./api
      - run: make test
      - run: make build-go
  # TODO: only run this on master (and not on tags)
  release:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
#      - run: make release
      - run: echo $CIRCLE_BRANCH
      - run: echo $CIRCLE_REPOSITORY_URL
      - run: echo $CIRCLE_PULL_REQUEST
      - run: ls -l ./api
      - run: git config user.email "bot@circleci.com"
      - run: git config user.name "CircleCI Bot"
      - run: git add .
      - run: git checkout $CIRCLE_BRANCH
      - run: git commit --allow-empty -m '[skip ci] Built release libraries'
      - run: git push origin $CIRCLE_BRANCH

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - release:
          requires:
            - test
