[package]
name = "evm-precompile-sha3fips"
version = "1.0.0-dev"
edition = "2021"
description = "SHA3 FIPS202 precompiles for EVM"

[dependencies]
tiny-keccak = { version = "2.0.2", features = ["fips202"] }
precompile-std = { version = "1.0.0-dev", path = "../precompile-std" }
