name: CI
on: [push]

jobs:
  build-shared-lib-ubuntu:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
#      - name: Cache build artifacts
#        uses: actions/cache@v3
#        with:
#          path: ~/.cache/sccache
#          key: ${{ runner.os }}-sccache
#      - name: Download sccache
#        run: |
#          wget https://github.com/mozilla/sccache/releases/download/0.2.13/sccache-0.2.13-x86_64-unknown-linux-musl.tar.gz
#          tar xf ./sccache-*.tar.gz
#          mv ./sccache*/sccache "$HOME/sccache"
      - name: Show version information
        run: |
          rustc --version; cargo --version; rustup --version
      - name: Setup protoc
        uses: arduino/setup-protoc@v1.1.2
      - uses: Swatinem/rust-cache@v2
      - name: Create release build of librustgo
        run: |
          make build-rust
      - name: Upload shared library
        uses: actions/upload-artifact@v2
        with:
          name: Shared library
          path: ./internal/api/libwasmvm.x86_64.so
  build-shared-lib-macos:
    runs-on: macOS-12
    steps:
      - uses: actions/checkout@v3
      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
      - name: Show version information
        run: |
          rustc --version; cargo --version; rustup --version
      - name: Setup protoc
        uses: arduino/setup-protoc@v1.1.2
      - uses: Swatinem/rust-cache@v2
      - name: Create release build of librustgo
        run: |
          make build-rust
      - name: Upload shared library
        uses: actions/upload-artifact@v2
        with:
          name: Shared library
          path: ./internal/api/libwasmvm.dylib
