name: CI
on: [push]

jobs:
  Build shared library:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
        name: Pull git submodules
      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
      - name: Cache build artifacts
        uses: actions/cache@v3
        with:
          path: ~/.cache/sccache
          key: ${{ runner.os }}-sccache
      - run: |
          rustup component add rust-src clippy
      - name: Download sccache
        run: |
          wget https://github.com/mozilla/sccache/releases/download/0.3.3/sccache-0.3.3-x86_64-unknown-linux-musl.tar.gz
          tar xf ./sccache-*.tar.gz
          mv ./sccache*/sccache "$HOME/sccache"
      - name: Show version information
      - run: |
          rustc --version; cargo --version; rustup --version

      - name: Create release build of librustgo
        run: |
          RUSTC_WRAPPER="$HOME/sccache" make build-rust
      - name: Upload shared library
        uses: actions/upload-artifact@v2
        with:
          name: Shared library
          path: ./internal/api/libwasmvm.x86_64.so
